/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as PromptsRouteImport } from './routes/prompts'
import { Route as MonitorRouteImport } from './routes/monitor'
import { Route as LogsRouteImport } from './routes/logs'
import { Route as ChannelsRouteImport } from './routes/channels'
import { Route as AccountsRouteImport } from './routes/accounts'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsChar123TabChar125RouteImport } from './routes/settings.{-$tab}'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const PromptsRoute = PromptsRouteImport.update({
  id: '/prompts',
  path: '/prompts',
  getParentRoute: () => rootRouteImport,
} as any)
const MonitorRoute = MonitorRouteImport.update({
  id: '/monitor',
  path: '/monitor',
  getParentRoute: () => rootRouteImport,
} as any)
const LogsRoute = LogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => rootRouteImport,
} as any)
const ChannelsRoute = ChannelsRouteImport.update({
  id: '/channels',
  path: '/channels',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountsRoute = AccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsChar123TabChar125Route =
  SettingsChar123TabChar125RouteImport.update({
    id: '/{-$tab}',
    path: '/{-$tab}',
    getParentRoute: () => SettingsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accounts': typeof AccountsRoute
  '/channels': typeof ChannelsRoute
  '/logs': typeof LogsRoute
  '/monitor': typeof MonitorRoute
  '/prompts': typeof PromptsRoute
  '/settings': typeof SettingsRouteWithChildren
  '/settings/{-$tab}': typeof SettingsChar123TabChar125Route
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accounts': typeof AccountsRoute
  '/channels': typeof ChannelsRoute
  '/logs': typeof LogsRoute
  '/monitor': typeof MonitorRoute
  '/prompts': typeof PromptsRoute
  '/settings': typeof SettingsRouteWithChildren
  '/settings/{-$tab}': typeof SettingsChar123TabChar125Route
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/accounts': typeof AccountsRoute
  '/channels': typeof ChannelsRoute
  '/logs': typeof LogsRoute
  '/monitor': typeof MonitorRoute
  '/prompts': typeof PromptsRoute
  '/settings': typeof SettingsRouteWithChildren
  '/settings/{-$tab}': typeof SettingsChar123TabChar125Route
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accounts'
    | '/channels'
    | '/logs'
    | '/monitor'
    | '/prompts'
    | '/settings'
    | '/settings/{-$tab}'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accounts'
    | '/channels'
    | '/logs'
    | '/monitor'
    | '/prompts'
    | '/settings'
    | '/settings/{-$tab}'
  id:
    | '__root__'
    | '/'
    | '/accounts'
    | '/channels'
    | '/logs'
    | '/monitor'
    | '/prompts'
    | '/settings'
    | '/settings/{-$tab}'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountsRoute: typeof AccountsRoute
  ChannelsRoute: typeof ChannelsRoute
  LogsRoute: typeof LogsRoute
  MonitorRoute: typeof MonitorRoute
  PromptsRoute: typeof PromptsRoute
  SettingsRoute: typeof SettingsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prompts': {
      id: '/prompts'
      path: '/prompts'
      fullPath: '/prompts'
      preLoaderRoute: typeof PromptsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/monitor': {
      id: '/monitor'
      path: '/monitor'
      fullPath: '/monitor'
      preLoaderRoute: typeof MonitorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logs': {
      id: '/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof LogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/channels': {
      id: '/channels'
      path: '/channels'
      fullPath: '/channels'
      preLoaderRoute: typeof ChannelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accounts': {
      id: '/accounts'
      path: '/accounts'
      fullPath: '/accounts'
      preLoaderRoute: typeof AccountsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/{-$tab}': {
      id: '/settings/{-$tab}'
      path: '/{-$tab}'
      fullPath: '/settings/{-$tab}'
      preLoaderRoute: typeof SettingsChar123TabChar125RouteImport
      parentRoute: typeof SettingsRoute
    }
  }
}

interface SettingsRouteChildren {
  SettingsChar123TabChar125Route: typeof SettingsChar123TabChar125Route
}

const SettingsRouteChildren: SettingsRouteChildren = {
  SettingsChar123TabChar125Route: SettingsChar123TabChar125Route,
}

const SettingsRouteWithChildren = SettingsRoute._addFileChildren(
  SettingsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountsRoute: AccountsRoute,
  ChannelsRoute: ChannelsRoute,
  LogsRoute: LogsRoute,
  MonitorRoute: MonitorRoute,
  PromptsRoute: PromptsRoute,
  SettingsRoute: SettingsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
