import type { OpenAiRemoteAccount } from "@/types/api";

export const openAiAccount: OpenAiRemoteAccount = {
  id: "openai-account-1",
  name: "Personal OpenAI",
  provider: "openai",
  base_url: "https://chatgpt.com",
  api_url: null,
  user_id: "account-123",
  user_token_configured: true,
  reauth_required: false,
  page_checkin_url: null,
  checkin_mode: "disabled",
  auto_checkin_enabled: false,
  auto_checkin_time: "00:05:00",
  low_balance_alert_threshold: 0,
  recharge_currency: "USD",
  remote_username: "codex@example.com",
  remote_display_name: null,
  last_balance_amount: null,
  last_sync_error: null,
  last_synced_at_ms: null,
  low_balance_alert_notified: false,
  last_balance_alert_at_ms: null,
  sort_order: 0,
  created_at_ms: 1,
  updated_at_ms: 1,
  account_id: "account-123",
  plan_type: "plus",
  token_expires_at_ms: null,
  quota_reset_available_count: 2,
  quota_windows: [
    {
      kind: "primary",
      limit_name: null,
      used_percent: 43,
      window_minutes: 10_080,
      resets_at_ms: Date.UTC(2026, 8, 10, 0, 0),
    },
    {
      kind: "additional",
      limit_name: "GPT-5.3-Codex-Spark",
      used_percent: 18,
      window_minutes: 300,
      resets_at_ms: Date.UTC(2026, 8, 3, 9, 33),
    },
    {
      kind: "additional",
      limit_name: "GPT-5.3-Codex-Spark",
      used_percent: 9,
      window_minutes: 10_080,
      resets_at_ms: Date.UTC(2026, 8, 10, 0, 0),
    },
  ],
};
